print('Enter your name')
myname=input()
print('How old are you')
age=input()
print('Your name is  '+  myname)
print('It is good to meet you, ' +myname)
print('Hello '+myname+ ' you are ' + str(age) +' Year old')
