#List 
print('Enter your cat1 name')
cat1=input()
print('Enter your cat2 name')
cat2=input()
print('Enter your cat3 name')
cat3=input()
print('Enter your cat4 name')
cat4=input()
print(cat1+''+cat2+''+cat3+''+cat4)
