tempFile = open('readfile.txt', 'w')
tempFile.write('Hello, Iam Sanket ....\n')
tempFile.close()
tempFile = open('readfile.txt', 'a')
tempFile.write('Nice to meet you again ..... !\nhave a wonderfull day......')
tempFile.close()
tempFile = open('readfile.txt')
fullcontent = tempFile.read()
tempFile.close()
print(fullcontent)
